### ISSUE TITLE
Implement type annotations

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/sodar-core#1461] opened 2024-08-01 06:52 UTC
### Problem

[Python type annotations](https://docs.python.org/3/library/typing.html) are very useful as they enable many static checks and eliminate whole classes of bugs. Plus, you get really nice type-safe editor autocompletion. There are [type annotations available for Django](https://github.com/sbdchd/django-types). `sodar-core` based sites cannot fully benefit from this as `django-sodar-core` package is missing type annotations.

### Solution

Implement type annotations and add static type checking as a CI check.

### Alternative Solutions

- keep as is
- provide a sodar-core-types package

### Additional Context

I would recommend [pyright](https://github.com/microsoft/pyright) over [mypy](https://github.com/python/mypy) as the type checking engine.

**Comment by holtgrewe** [comment] 2024-08-01 06:53
CC @tedil who is an expert in Python type annotations

**Comment by mikkonie** [comment] 2024-08-01 12:32
Dupe of #568, closing.

**Closed as completed by mikkonie** 2024-08-01 12:32 UTC
Labels: duplicate, feature
